server:
    port: 3000
    servlet:
        context-path: /api

spring:
    datasource:
        url: jdbc:h2:file:./src/main/resources/db/bibliothequeDB2
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
    main:
        allow-circular-references: true

security:
    jwt:
        token:
            secret-key: antituconstitutionnellement

springdoc: 
    api-docs: 
        path: /doc

management :
    endpoint:
        health:
            cache:
                time-to-live: 10s
            show-details: always
        info:
            cache:
                time-to-live: 10s
    endpoints :
        web: 
            exposure:  
                include: info,health
            discovery:
                enabled: true

info: 
    version: 0.0
    app:
        context: bibliothequespring