name: monAPI cicd

on:
  push:
    branches:
      - develop
    tags: 
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Show current directory contents
        run: ls -l
      - name: Build with Maven
        run: mvn clean install

  build_dev_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Development Docker image
        env:
          TAG: ${{ github.ref_name }}
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/heads/develop' ]]; then
            docker build -t monapi:dev .
          else
            echo "No Docker development image built."
          fi

  build_prod_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Prod Docker image
        env:
          TAG: ${{ github.ref_name }}
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/tags/v*.*.*' ]]; then
            docker build -t monapi:${TAG} .
          else
            echo "No Docker Prod image built."
          fi

  push_dev_image:
    runs-on: ubuntu-latest
    needs: build_dev_image
    steps:
      - name: Push Development Docker image
        env:
          TAG: ${{ github.ref_name }}
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/heads/develop' ]]; then
            docker tag monapi:dev ycostarddev/monapi:dev
            docker push ycostarddev/monapi:dev
          else
            echo "No Docker development image pushed."
          fi

  push_prod_image:
    runs-on: ubuntu-latest
    needs: build_prod_image
    steps:
      - name: Push Prod Docker image
        env:
          TAG: ${{ github.ref_name }}
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/tags/v*.*.*' ]]; then
            docker tag monapi:${TAG} ycostarddev/monapi:${TAG}
            docker push ycostarddev/monapi:${TAG}
          else
            echo "No Docker Prod image pushed."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: push_prod_image
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'tag')
    steps:
      - name: Deployment step (manual)
        run: echo "Deploying to server..."
        # Add your deployment scripts/commands here
