name: monAPI cicd

on:
  push:
    branches:
      - develop
    tags: 
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

  build_dev_image:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Development Docker image
        run: docker build -t monapi:dev .

  build_prod_image:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Prod Docker image
        run: docker build -t monapi:${{ github.ref_name }} .

  push_dev_image:
    runs-on: ubuntu-latest
    needs: build_dev_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Push Development Docker image
        run: |
          docker tag monapi:dev ycostarddev/monapi:dev
          docker push ycostarddev/monapi:dev

  push_prod_image:
    runs-on: ubuntu-latest
    needs: build_prod_image
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Push Prod Docker image
        run: |
          docker tag monapi:${{ github.ref_name }} ycostarddev/monapi:${{ github.ref_name }}
          docker push ycostarddev/monapi:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: push_prod_image
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'tag')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deployment step (manual)
        run: echo "Deploying to server..."