name: monAPI cicd

on:
  push:
    branches:
      - develop
    tags: 
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current directory contents
        run: ls -l

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build Development Docker image
        if: github.ref == 'refs/heads/develop'
        run: |
          docker build -t monapi:dev .

      - name: Build Prod Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker build -t monapi:${TAG} .

      - name: Push Development Docker image
        if: github.ref == 'refs/heads/develop'
        run: |
          docker tag monapi:dev ycostarddev/monapi:dev
          docker push ycostarddev/monapi:dev

      - name: Push Prod Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag monapi:${TAG} ycostarddev/monapi:${TAG}
          docker push ycostarddev/monapi:${TAG}

      - name: Deployment step (manual)
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'tag')
        run: echo "Deploying to server..."
        # Add your deployment scripts/commands here